import pickle
import sqlite3

from config import DB_PATH


def execute(query):
    dbPath = DB_PATH
    connection = sqlite3.connect(dbPath)
    cursorobj = connection.cursor()
    try:
        cursorobj.execute(query)
        result = cursorobj.fetchall()
        connection.commit()
    except Exception:
        raise
    connection.close()
    return result


def format_list(list, keys):
    cleaned = []
    for i in range(len(list)):
        d = {}
        for k in keys:
            d[k] = list[i]
        list.append(d)


def format(list, keys=None):
    pass

def graph(id=None, user_id=None, name=None):
    if id:
        q = 'id=' + str(id)
    elif user_id and name:
        q = 'user_id=' + str(user_id) + "and name='" + name
    else:
        # Raise error.
        pass
    results = query('graphs', query=q)
    graph = format_list(results, ['id', 'created', 'name', 'user_id', 'color'])


def query(table, query=None, columns="*"):
    q = "select %s from %s" % (columns, table)
    if query:
        q += " where %s" % query
    q += ";"
    return execute(q)


def set_up():
        execute("create table users(id integer primary key not null, " + \
                        "name varchar(20) unique not null, " + \
                        "alpha references graphs(id), " + \
                        "bravo references graphs(id), " + \
                        "charlie references graphs(id), " + \
                        "api_key varchar unique);")
        execute("create table graphs(id integer primary key not null, " + \
                        "created datetime default current_timestamp," + \
                        "name varchar(20), " + \
                        "user_id references users(id) not null, " + \
                        "color blob, " + \
                        "lambda blob);")
        execute("create table events(id integer primary key not null, " + \
                        "graph_id references graphs(id) not null, " + \
                        "date datetime not null, " + \
                        "data blob);")
        init_data()


def init_data():
        execute("insert into users('name') values('ingrid');")
        execute("insert into users('name') values('bmac');")
        execute("insert into graphs('name', 'user_id') values ('foo', 1);")
        execute("insert into graphs('name', 'user_id') values ('exercise', 2);")
        execute("insert into graphs('name', 'user_id') values ('gh', 2);")
        execute("insert into events('graph_id', 'date') values (1, '2007-01-01');")
        execute("insert into events('graph_id', 'date', 'data') values (2, '2013-06-01', 5);")
        execute("insert into events('graph_id', 'date', 'data') values (2, '2013-06-02', 5);")
        execute("update users set alpha='exercise' where id=2;")
        execute("update users set bravo='github' where id=2;")
        execute("insert into events('graph_id', 'date', 'data') values (3,'2013-01-13', 1);")
        execute("insert into events('graph_id', 'date', 'data') values (3,'2013-01-14', 2);")
        execute("insert into events('graph_id', 'date', 'data') values (3,'2013-01-15', 1);")
        execute("insert into events('graph_id', 'date', 'data') values (3,'2013-01-16', 7);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-01-17', 1);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-01-18', 2);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-01-19', 7);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-01-20', 1);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-01-21', 1);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-01-22', 1);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-01-23', 3);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-01-24', 1);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-01-25', 1);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-01-26', 1);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-01-27', 1);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-01-28', 3);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-01-29', 3);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-01-30', 2);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-01-31', 2);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-02-01', 2);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-02-02', 1);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-02-03', 5);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-02-04', 1);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-02-05', 6);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-02-06', 4);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-02-07', 1);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-02-08', 1);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-02-09', 2);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-02-10', 1);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-02-11', 1);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-02-12', 1);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-02-13', 1);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-02-14', 1);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-02-15', 1);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-02-16', 1);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-02-17', 3);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-02-18', 2);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-02-19', 1);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-02-20', 1);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-02-21', 1);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-02-22', 3);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-02-23', 1);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-02-25', 2);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-02-26', 1);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-02-27', 1);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-02-28', 1);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-03-01', 2);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-03-02', 1);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-03-03', 1);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-03-04', 1);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-03-05', 1);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-03-06', 1);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-03-07', 1);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-03-08', 1);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-03-09', 1);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-03-10', 1);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-03-11', 1);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-03-12', 1);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-03-13', 0);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-03-14', 1);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-03-15', 1);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-03-16', 1);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-03-17', 7);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-03-18', 2);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-03-19', 1);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-03-20', 1);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-03-21', 1);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-03-22', 0);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-03-23', 1);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-03-24', 3);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-03-25', 1);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-03-26', 1);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-03-27', 2);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-03-28', 1);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-03-29', 0);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-03-30', 1);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-03-31', 1);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-04-01', 1);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-04-02', 1);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-04-03', 1);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-04-04', 1);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-04-05', 2);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-04-06', 1);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-04-09', 1);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-04-10', 2);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-04-11', 1);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-04-12', 1);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-04-13', 1);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-04-14', 1);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-04-15', 1);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-04-16', 0);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-04-17', 0);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-04-18', 0);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-04-19', 0);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-04-20', 3);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-04-21', 1);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-04-22', 1);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-04-23', 0);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-04-24', 0);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-04-25', 1);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-04-26', 1);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-04-27', 1);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-04-28', 2);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-04-29', 0);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-04-30', 1);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-05-01', 1);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-05-02', 1);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-05-03', 0);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-05-04', 0);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-05-05', 1);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-05-06', 1);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-05-07', 2);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-05-08', 1);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-05-09', 0);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-05-10', 0);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-05-11', 0);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-05-12', 1);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-05-13', 0);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-05-14', 1);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-05-15', 0);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-05-16', 5);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-05-17', 1);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-05-18', 0);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-05-19', 0);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-05-20', 0);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-05-21', 0);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-05-22', 0);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-05-23', 0);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-05-24', 0);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-05-25', 1);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-05-26', 0);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-05-27', 2);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-05-28', 0);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-05-29', 0);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-05-30', 1);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-05-31', 6);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-06-01', 1);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-06-02', 1);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-06-03', 1);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-06-04', 1);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-06-05', 1);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-06-06', 2);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-06-07', 3);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-06-08', 0);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-06-09', 1);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-06-10', 1);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-06-11', 5);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-06-12', 1);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-06-13', 1);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-06-14', 1);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-06-15', 3);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-06-16', 0);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-06-17', 1);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-06-18', 0);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-06-19', 1);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-06-20', 1);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-06-21', 0);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-06-22', 0);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-06-23', 1);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-06-24', 0);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-06-25', 1);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-06-26', 1);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-06-27', 1);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-06-28', 1);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-06-29', 2);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-06-30', 1);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-07-01', 1);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-07-02', 3);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-07-03', 0);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-07-04', 1);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-07-05', 1);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-07-06', 0);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-07-07', 0);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-07-08', 0);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-07-09', 0);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-07-10', 1);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-07-11', 0);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-07-12', 0);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-07-13', 7);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-07-14', 1);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-07-16', 0);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-07-17', 3);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-07-18', 1);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-07-19', 0);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-07-20', 0);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-07-21', 0);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-07-22', 8);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-07-23', 1);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-07-24', 1);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-07-25', 2);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-07-26', 0);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-07-27', 4);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-07-28', 1);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-07-29', 3);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-07-30', 3);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-07-31', 1);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-08-01', 1);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-08-02', 3);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-08-03', 5);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-08-04', 1);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-08-05', 1);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-08-06', 1);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-08-07', 6);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-08-08', 2);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-08-09', 1);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-08-11', 1);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-08-12', 3);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-08-13', 2);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-08-14', 1);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-08-15', 2);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-08-16', 2);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-08-17', 4);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-08-18', 6);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-08-19', 5);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-08-20', 0);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-08-21', 5);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-08-22', 1);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-08-23', 1);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-08-24', 0);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-08-25', 2);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-08-26', 1);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-08-27', 1);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-08-28', 1);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-08-29', 0);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-08-30', 2);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-08-31', 2);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-09-01', 2);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-09-02', 1);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-09-03', 5);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-09-04', 0);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-09-05', 0);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-09-06', 1);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-09-07', 0);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-09-08', 1);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-09-09', 9);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-09-10', 3);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-09-11', 1);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-09-12', 5);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-09-13', 5);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-09-14', 2);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-09-15', 5);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-09-16', 6);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-09-17', 3);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-09-18', 3);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-09-19', 3);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-09-20', 2);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-09-21', 2);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-09-22', 8);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-09-23', 9);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-09-24', 2);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-09-25', 5);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-09-26', 1);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-09-27', 2);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-09-28', 1);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-10-01', 3);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-10-02', 3);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-10-03', 3);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-10-04', 1);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-10-05', 6);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-10-06', 4);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-10-07', 2);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-10-08', 1);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-10-10', 2);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-10-11', 2);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-10-12', 3);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-10-13', 1);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-10-16', 4);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-10-17', 6);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-10-18', 1);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-10-19', 2);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-10-20', 4);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-10-21', 8);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-10-22', 9);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-10-23', 1);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-10-24', 1);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-10-26', 2);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-10-27', 6);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-10-28', 4);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-10-29', 4);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-10-30', 1);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-11-01', 2);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-11-02', 0);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-11-03', 2);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-11-04', 4);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-11-05', 1);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-11-08', 1);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-11-09', 1);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-11-10', 3);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-11-11', 3);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-11-12', 4);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-11-13', 2);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-11-14', 1);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-11-15', 6);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-11-16', 1);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-11-17', 1);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-11-18', 5);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-11-19', 2);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-11-20', 1);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-11-21', 2);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-11-22', 2);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-11-23', 2);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-11-24', 1);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-11-25', 3);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-11-26', 1);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-11-27', 1);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-11-28', 2);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-11-29', 0);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-11-30', 2);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-12-01', 5);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-12-02', 1);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-12-03', 4);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-12-04', 1);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-12-06', 2);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-12-07', 3);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-12-08', 2);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-12-09', 4);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-12-10', 1);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-12-11', 4);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-12-12', 4);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-12-13', 1);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-12-14', 1);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-12-15', 1);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-12-16', 1);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-12-17', 5);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-12-18', 1);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-12-19', 4);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-12-20', 0);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-12-21', 2);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-12-22', 2);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-12-23', 1);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-12-24', 1);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-12-25', 1);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-12-26', 1);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-12-27', 1);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-12-28', 0);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-12-29', 0);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-12-30', 4);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2013-12-31', 2);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2014-01-01', 2);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2014-01-02', 4);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2014-01-03', 3);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2014-01-04', 6);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2014-01-05', 2);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2014-01-06', 1);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2014-01-07', 1);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2014-01-08', 1);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2014-01-09', 1);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2014-01-10', 3);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2014-01-11', 2);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2014-01-12', 3);")
        execute("insert into events('graph_id', 'date', 'data') values (3, '2014-01-13', 0);")

def tear_down():
    try:
        execute("drop table users;")
    except:
        pass
    try:
        execute("drop table graphs;")
    except:
        pass
    try:
        execute("drop table events;")
    except:
        pass
